
name: Check for dwc terms
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'feature/events'
#on:
#  schedule:
#    - cron: '0 0 1 * *'
jobs:
  updateterms:
    runs-on: ubuntu-latest
    outputs:
      file-diff1: ${{ steps.check-file-diff-steps.outputs.file-diff1 }}
      file-diff2: ${{ steps.check-file-diff-steps.outputs.file-diff2 }}
      file-diff3: ${{ steps.check-file-diff-steps.outputs.file-diff3 }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install project dependencies
        run: |
          python -m pip install poetry
          poetry install
      - name: Call script to update terms
        run: |
          cd ${{ github.workspace }}
          poetry run update-terms
      - id: check-file-diff-step
        name: Check file diff
        run: |
          echo ${{ github.workspace }}
          cd ${{ github.workspace }}/src/dwcahandler/dwca/terms
          diff1=$(git diff --name-only extension-register.csv)
          echo $diff1
          diff2=$(git diff --name-only class-rowtype.csv)
          echo $diff2
          diff3=$(git diff --name-only terms.csv)
          echo $diff3
          {
            echo "file-diff1=$diff1"
            echo "file-diff2=$diff2"
            echo "file-diff3=$diff3"
           } >> $GITHUB_OUTPUT
      - name: Create pull request
        if: ${{ (steps.check-file-diff-step.outputs.file-diff1 != '') || 
                (steps.check-file-diff-step.outputs.file-diff2 != '') ||
                (steps.check-file-diff-step.outputs.file-diff3 != '') }}
        run: |
          BRANCH="gbif-extension-update-$(date +'%Y-%m-%dT%H%M%S')"
          git checkout -b "$BRANCH"
          git config user.name github-actions
          git config user.email github-actions@github.com
          cd ${{ github.workspace }}/src/dwcahandler/dwca/terms
          CHANGEDFILES="Please review the changes to the following files: "
          if [ ${{ steps.check-file-diff-step.outputs.file-diff1 }} != '' ]
          then
            git commit -m "New updates from gbif extensions updates" extension-register.csv
            CHANGEDFILES="$CHANGEDFILES ${{ steps.check-file-diff-step.outputs.file-diff1 }} "
          fi
          if [ ${{ steps.check-file-diff-step.outputs.file-diff2 }} != '' ]
          then
            git commit -m "New updates from gbif extensions updates" class-rowtype.csv
            CHANGEDFILES="$CHANGEDFILES ${{ steps.check-file-diff-step.outputs.file-diff2 }} "
          fi
          if [ ${{ steps.check-file-diff-step.outputs.file-diff3 }} != '' ]
          then
            git commit -m "New updates from gbif extensions updates" terms.csv
            CHANGEDFILES="$CHANGEDFILES ${{ steps.check-file-diff-step.outputs.file-diff3 }} "          
          fi          
          git push origin $BRANCH
          gh pr create -H $BRANCH -B main --title "New updates to gbif extension on $BRANCH" --body "$CHANGEDFILES"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
